"""Add post-quantum cryptography features

Revision ID: 002
Revises: 001
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create server_kyber_keys table
    op.create_table('server_kyber_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant', sa.String(length=50), nullable=False),
    sa.Column('public_key', sa.String(length=4096), nullable=False),
    sa.Column('secret_key', sa.String(length=4096), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant')
    )
    op.create_index(op.f('ix_server_kyber_keys_id'), 'server_kyber_keys', ['id'], unique=False)
    
    # Add kem_ciphertext column to messages table
    op.add_column('messages', sa.Column('kem_ciphertext', sa.String(length=4096), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove kem_ciphertext column from messages table
    op.drop_column('messages', 'kem_ciphertext')
    
    # Drop server_kyber_keys table
    op.drop_index(op.f('ix_server_kyber_keys_id'), table_name='server_kyber_keys')
    op.drop_table('server_kyber_keys')
    
    # ### end Alembic commands ###
